#!/usr/bin/env python3

import os
import dotenv
import tweepy
from tweepy import OAuthHandler



def login_to_twitter():

    dotenv.load_dotenv()

    consumer_key = os.getenv("twitter_api_key")
    consumer_secret = os.getenv("twitter_api_secret_key")
    access_token = os.getenv("twitter_access_token")
    access_token_secret = os.getenv("twitter_access_token_secret"))

    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)

    api = tweepy.API(auth)

    return api


def scrape_tweets(api, keywords):

    pass


api = login_to_twitter()

test = scrape_tweets(api, ['Mexico', 'United Airlines'])

print(test)



